# <u>WOMEN CLOTHS REVIEW</u>

## Import Dependencies

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Load Data

In [11]:
data = pd.read_csv('/content/Womens Clothing E-Commerce Reviews.csv', index_col = 0)

In [12]:
data.rename(columns = {
    'Review Text': 'Review',
    'Recommended IND': 'Recommended',
    'Positive Feedback Count': 'Positive Feedback',
    'Division Name': 'Division',
    'Department Name': 'Department',
    'Class Name': 'Category'},
            inplace = True)

In [13]:
data.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [14]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 2.0+ MB


In [15]:
data.shape

(23486, 10)

## Missing Values

In [16]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [17]:
data[data['Review'] == ''] = np.NaN

In [18]:
data['Review'].fillna('No Review', inplace = True)

In [19]:
data.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [20]:
data['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

## Define Target(y) and Feature(X)

In [21]:
data.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [22]:
X = data['Review']

In [23]:
y = data['Rating']

In [24]:
data['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

## Train Test Split

In [25]:
from sklearn.model_selection import train_test_split

In [108]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 182529)

In [109]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Feature text coversion to tokens

In [110]:
from sklearn.feature_extraction.text import CountVectorizer

In [111]:
cv = CountVectorizer(
                lowercase = True,
                analyzer = 'word',
                ngram_range = (2, 3),
                stop_words = 'english',
                max_features = 5000
                    )

In [112]:
X_train = cv.fit_transform(X_train)

In [113]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'years old',
       'yellow color', 'yoga pants'], dtype=object)

In [114]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [115]:
X_test = cv.fit_transform(X_test)

In [116]:
cv.get_feature_names_out()

array(['0p fit', '10 12', '10 12 12', ..., 'years come',
       'yesterday store', 'yoga pants'], dtype=object)

In [117]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

## Train Model

In [118]:
from sklearn.naive_bayes import MultinomialNB

In [119]:
model = MultinomialNB()

In [120]:
model.fit(X_train, y_train)

MultinomialNB()

## Model Prediction

In [121]:
y_pred = model.predict(X_test)

In [122]:
y_pred.shape

(7046,)

In [123]:
y_pred

array([1., 1., 1., ..., 1., 1., 1.])

## Get Probability of Each Predicted Class

In [124]:
model.predict_proba(X_test)

array([[0.02554725, 0.97445275],
       [0.13429194, 0.86570806],
       [0.00101538, 0.99898462],
       ...,
       [0.09367675, 0.90632325],
       [0.01061971, 0.98938029],
       [0.22475669, 0.77524331]])

## Model Evaluation

In [125]:
from sklearn.metrics import confusion_matrix, classification_report

In [126]:
print(confusion_matrix(y_test, y_pred))

[[ 517 1066]
 [ 877 4586]]


In [127]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.37      0.33      0.35      1583
         1.0       0.81      0.84      0.83      5463

    accuracy                           0.72      7046
   macro avg       0.59      0.58      0.59      7046
weighted avg       0.71      0.72      0.72      7046



## Recategorize Rating as Poor(0) and Good(1)

In [128]:
data_recategorized = data.replace({'Rating': {1:0, 2:0, 3:0, 4:1, 5:1}})

In [129]:
y = data_recategorized['Rating']

In [130]:
X = data_recategorized['Review']

## Train Test Split

In [131]:
from sklearn.model_selection import train_test_split

In [147]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, stratify = y, random_state = 18529)

In [148]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((16440,), (7046,), (16440,), (7046,))

## Feature text coversion to tokens

In [149]:
from sklearn.feature_extraction.text import CountVectorizer

In [150]:
cv = CountVectorizer(
                lowercase = True,
                analyzer = 'word',
                ngram_range = (2, 3),
                stop_words = 'english',
                max_features = 5000
                    )

In [151]:
X_train = cv.fit_transform(X_train)

In [152]:
X_test = cv.fit_transform(X_test)

## Re-Train Model

In [153]:
from sklearn.naive_bayes import MultinomialNB

In [154]:
model = MultinomialNB()

In [155]:
model.fit(X_train, y_train)

MultinomialNB()

## Model Prediction

In [156]:
y_pred = model.predict(X_test)

In [157]:
y_pred.shape

(7046,)

In [158]:
y_pred

array([0., 1., 1., ..., 1., 1., 0.])

## Model Evaluation

In [159]:
from sklearn.metrics import confusion_matrix, classification_report

In [160]:
print(confusion_matrix(y_test, y_pred))

[[ 428 1155]
 [1110 4353]]


In [161]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.28      0.27      0.27      1583
         1.0       0.79      0.80      0.79      5463

    accuracy                           0.68      7046
   macro avg       0.53      0.53      0.53      7046
weighted avg       0.68      0.68      0.68      7046

